namespace Microsoft.FailoverClusters.Framework;

public enum ResourceKind
{
	GenericApplication = 1,
	GenericService = 2,
	PhysicalDisk = 3,
	IPAddress = 4,
	IPv6Address = 5,
	IPv6TunnelAddress = 6,
	NetworkName = 7,
	FileServer = 8,
	FileShareWitness = 9,
	CloudWitness = 10,
	DhcpService = 11,
	Msmsq = 12,
	MsmsqTrigger = 13,
	Dtc = 14,
	WinsService = 15,
	GenericScript = 16,
	VolumeShadowCopyServiceTask = 17,
	IScsiNameService = 18,
	IScsiTarget = 19,
	NfsShare = 20,
	VirtualMachine = 21,
	VirtualMachineConfiguration = 22,
	DistributedFileSystem = 23,
	DfsReplicatedFolder = 24,
	ScaleOutFileServer = 25,
	DistributedNetworkName = 26,
	VirtualMachineReplicationBroker = 27,
	NetworkFileSystem = 28,
	StoragePool = 29,
	TaskScheduler = 30,
	ClusterAwareUpdating = 31,
	HyperVNetworkVirtualizationProviderAddress = 32,
	NetworkAddressTranslator = 33,
	DisjointIPv4Address = 34,
	DisjointIPv6Address = 35,
	StorageReplica = 36,
	HealthService = 37,
	StorageQoS = 38,
	HyperVClusterWmi = 39,
	VirtualMachineReplicationCoordinator = 40,
	SDDCManagement = 41,
	CrossClusterOrchestrator = 42,
	InfrastructureFileServer = 43,
	ClusterFileSystem = 65539,
	Other = 9999,
	[Filterable(false)]
	Fetching = 1073741824
}
